### ISSUE TITLE
Loading in the server

### ISSUE THREAD

**Issue by MeaLeigh** [TerbSEC/HealthbarUI#4]
I have this strange issue where the healthbar ui shows up on the loading screen before the player loads into the server. I have had many people try and put this on their servers to test it and they all run into the same issue. I was just wondering if it was something I am doing wrong?

**Comment by TerbSEC** [comment]
You are not really doing anything wrong. If you have an variable or something. That can tell the script when you are loaded in, and then it can show. Or you can set an wait to the script. Since this is a discontinued script. Then I can't really help anymore
